# Доступ только Authorized Required, @ auth_required
GET http://127.0.0.1:1987/movies/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxZVx1MDQzYlx1MDQzNVx1MDQzMyIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY1Nzk3MzkwOH0.OdIdizAoq_SC52SyBBKnasbsCdAbTs0NWQ96OyeVics

###

# Доступ только Authorized Required, @ auth_required
GET http://127.0.0.1:1987/movies/?director_id=11
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzOFx1MDQzYVx1MDQ0Mlx1MDQzZVx1MDQ0MCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3MDE3OTMzfQ.bRkNJcnfFW6RtTbiRxaK1Vtc0VN47Rx7wn6msIeWBdM

###

# Доступ только Authorized Required, @ auth_required
GET http://127.0.0.1:1987/movies/?genre_id=18
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzOFx1MDQzYVx1MDQ0Mlx1MDQzZVx1MDQ0MCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3MDE3OTMzfQ.bRkNJcnfFW6RtTbiRxaK1Vtc0VN47Rx7wn6msIeWBdM

###

# Доступ только Authorized Required, @ auth_required
GET http://127.0.0.1:1987/movies/?year=2018
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzOFx1MDQzYVx1MDQ0Mlx1MDQzZVx1MDQ0MCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3MDE3OTMzfQ.bRkNJcnfFW6RtTbiRxaK1Vtc0VN47Rx7wn6msIeWBdM

###

# Доступ только Authorized Required, @ auth_required
# Доступ только Role admin Required, @ admin_required
POST http://127.0.0.1:1987/movies/
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxZVx1MDQzYlx1MDQzNVx1MDQzMyIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY1Nzk3MzkwOH0.OdIdizAoq_SC52SyBBKnasbsCdAbTs0NWQ96OyeVics

{
  "id": 21,
  "title": "Игра",
  "description": "Жизнь банкира превращается в ад, но, возможно, это кем-то спланировано.",
  "trailer": "https://www.kinopoisk.ru/film/12198/Y",
  "year": 1997,
  "rating": 8.3,
  "genre_id": 6,
  "director_id": 21
}

###

# Доступ только Authorized Required, @ auth_required
GET http://127.0.0.1:1987/movies/10
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzOFx1MDQzYVx1MDQ0Mlx1MDQzZVx1MDQ0MCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3MDE3OTMzfQ.bRkNJcnfFW6RtTbiRxaK1Vtc0VN47Rx7wn6msIeWBdM

###

# Доступ только Authorized Required, @ auth_required
# Доступ только Role admin Required, @ admin_required
PUT http://127.0.0.1:1987/movies/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzOFx1MDQzYVx1MDQ0Mlx1MDQzZVx1MDQ0MCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3MDE3OTMzfQ.bRkNJcnfFW6RtTbiRxaK1Vtc0VN47Rx7wn6msIeWBdM

{
  "id": 21,
  "title": "Игра",
  "description": "Жизнь банкира превращается в ад, но, возможно, это кем-то спланировано.",
  "trailer": "https://www.kinopoisk.ru/film/12198/",
  "year": 1997,
  "rating": 8.3,
  "genre_id": 6,
  "director_id": 21
}

###

# Доступ только Authorized Required, @ auth_required
# Доступ только Role admin Required, @ admin_required
DELETE http://127.0.0.1:1987/movies/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzOFx1MDQzYVx1MDQ0Mlx1MDQzZVx1MDQ0MCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3MDE3OTMzfQ.bRkNJcnfFW6RtTbiRxaK1Vtc0VN47Rx7wn6msIeWBdM
